import { Problem, Solution, Pilot, ReplicationRequest } from "./types";

export const SEED_PROBLEMS: Problem[] = [
  {
    id: "prob-01",
    code: "PRB-2026-081",
    title: "Canopy-Penetrating Drone Surveillance for Border Outposts",
    department: "Division of Precision Remote Sensing & Border Technologies",
    ministry: "Department of Military Affairs / ICAR Joint Initiative",
    domain: "DroneTech",
    description:
      "Dense forest canopies and undulating mountain terrain severely impair standard electro-optical reconnaissance. The department requires an autonomous low-altitude UAV equipped with multispectral penetration imaging, onboard edge inference, and encrypted mesh telemetry to detect concealed ground movements beneath thick foliage without relying on cellular networks.",
    desiredOutcome:
      "Operational prototype demonstrating >90% target classification accuracy beneath closed tree canopies at altitudes between 50m–120m AGL, with latency under 1.2 seconds from detection to ground station alert.",
    budgetBand: "₹25L–₹50L",
    targetTRL: "TRL-6",
    deadline: "2026-10-30",
    createdAt: "2026-09-01",
    submissionCount: 3,
    status: "evaluating",
  },
  {
    id: "prob-02",
    code: "PRB-2026-042",
    title: "Autonomous Multispectral Weed Detection & Precision Spot Spraying",
    department: "Directorate of Crop Protection & Farm Mechanization",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    domain: "AgriTech",
    description:
      "Excessive broadcast spraying of herbicides causes chemical runoff, soil degradation, and unnecessary farmer expenditure. We seek a tractor-mountable or autonomous robotic boom system integrating optical camera arrays with real-time weed vs. crop segmentation to actuate precision micro-nozzles.",
    desiredOutcome:
      "Reduction of chemical herbicide volume by at least 65% across pulse and wheat test fields, operating at standard tractor speeds of 6–10 km/h with sub-centimeter nozzle trigger precision.",
    budgetBand: "₹10L–₹25L",
    targetTRL: "TRL-5",
    deadline: "2026-11-15",
    createdAt: "2026-09-05",
    submissionCount: 5,
    status: "open",
  },
  {
    id: "prob-03",
    code: "PRB-2026-105",
    title: "Edge IoT Cold-Chain Temperature Telemetry for Remote Vaccine Delivery",
    department: "National Health Mission Infrastructure Cell",
    ministry: "Ministry of Health & Family Welfare",
    domain: "HealthTech",
    description:
      "Last-mile vaccine delivery across northeastern hilly corridors suffers from unrecorded temperature excursions. The mission requires tamper-evident, ultra-low power IoT dataloggers with satellite or store-and-forward BLE sync that continuously log ambient and vaccine core temperature.",
    desiredOutcome:
      "Continuous logging within ±0.2°C accuracy between -20°C to +8°C, minimum 90-day battery life, and automated cryptographic audit trail generation on arrival at primary health centres.",
    budgetBand: "< ₹10L",
    targetTRL: "TRL-6",
    deadline: "2026-10-15",
    createdAt: "2026-08-20",
    submissionCount: 4,
    status: "pilot_active",
  },
];

export const SEED_SOLUTIONS: Solution[] = [
  {
    id: "sol-01",
    problemId: "prob-01",
    startupId: "user-startup-01",
    startupName: "AeroKisan Technologies Pvt Ltd",
    dpiitNumber: "DIPP98234",
    dpiitVerified: true,
    location: "Bengaluru, Karnataka",
    title: "KisanDrishya-X: Dual Multispectral Hexacopter with Edge Thermal Segmentation",
    abstract:
      "A ruggedized carbon-composite hexacopter carrying synchronized shortwave-infrared (SWIR) and thermal sensors. Onboard NVIDIA Jetson Orin compute executes quantized YOLO-v8 segmentation to detect warm canopy anomalies and identify obstructed vehicle tracks under dense forest foliage.",
    claimedTRL: "TRL-6",
    proposedCost: 2850000,
    proposedDurationWeeks: 8,
    submittedAt: "2026-09-08",
    matchScore: 0.92,
    matchExplanation:
      "Strong technical alignment with multispectral canopy penetration, low-altitude flight autonomy, and onboard edge compute. Proposes verified SWIR optics matching problem specification criteria.",
    matchedKeywords: [
      "multispectral penetration imaging",
      "onboard edge inference",
      "forest canopy classification",
      "encrypted telemetry",
      "TRL-6 prototype",
    ],
    pdfUrl: "/proposals/AeroKisan_Canopy_Surveillance_Proposal.pdf",
    status: "shortlisted",
    rubricScore: {
      technicalMerit: 28,
      costRealism: 18,
      teamCapability: 19,
      timelineViability: 27,
      total: 92,
    },
  },
  {
    id: "sol-02",
    problemId: "prob-01",
    startupId: "user-startup-02",
    startupName: "Drishti Vision Labs Pvt Ltd",
    dpiitNumber: "DIPP77120",
    dpiitVerified: true,
    location: "Hyderabad, Telangana",
    title: "AeroSight foliage-penetrating optical payload with LiDAR point-cloud clustering",
    abstract:
      "Lightweight LiDAR payload mounted on tethered and battery-powered multirotors. Employs 16-channel solid-state LiDAR with return pulse filtering to strip away tree branches and reveal ground elevation changes.",
    claimedTRL: "TRL-5",
    proposedCost: 3200000,
    proposedDurationWeeks: 10,
    submittedAt: "2026-09-09",
    matchScore: 0.84,
    matchExplanation:
      "High capability in LiDAR-based canopy penetration; however, proposed payload weight slightly exceeds single-battery endurance target. Excellent team academic credentials from IIIT Hyderabad.",
    matchedKeywords: [
      "foliage penetration",
      "solid-state LiDAR",
      "edge point-cloud processing",
      "autonomous altitude hold",
    ],
    pdfUrl: "/proposals/Drishti_LiDAR_Canopy_Proposal.pdf",
    status: "submitted",
    rubricScore: {
      technicalMerit: 26,
      costRealism: 16,
      teamCapability: 18,
      timelineViability: 24,
      total: 84,
    },
  },
  {
    id: "sol-03",
    problemId: "prob-01",
    startupId: "user-startup-03",
    startupName: "Bharat Robotics & AI Systems",
    dpiitNumber: "DIPP44901",
    dpiitVerified: false,
    location: "Pune, Maharashtra",
    title: "Fixed-Wing UAV with optical zoom and satellite relay for regional monitoring",
    abstract:
      "Long-endurance composite fixed-wing UAV capable of 90-minute cruise. Employs high-magnification optical sensors with satellite backhaul for high-altitude boundary tracking.",
    claimedTRL: "TRL-4",
    proposedCost: 4500000,
    proposedDurationWeeks: 14,
    submittedAt: "2026-09-07",
    matchScore: 0.71,
    matchExplanation:
      "Solution focuses on high-altitude surveillance rather than low-altitude foliage penetration. Requires extensive runway infrastructure; minimal edge compute detailed.",
    matchedKeywords: [
      "boundary reconnaissance",
      "fixed-wing airframe",
      "satellite link",
    ],
    pdfUrl: "/proposals/BharatRobotics_FixedWing_Proposal.pdf",
    status: "submitted",
    rubricScore: {
      technicalMerit: 20,
      costRealism: 15,
      teamCapability: 17,
      timelineViability: 19,
      total: 71,
    },
  },
];

export const SEED_PILOTS: Pilot[] = [
  {
    id: "plt-01",
    code: "PLT-2026-012",
    problemId: "prob-01",
    solutionId: "sol-01",
    startupId: "user-startup-01",
    startupName: "AeroKisan Technologies Pvt Ltd",
    dpiitNumber: "DIPP98234",
    department: "Division of Precision Remote Sensing & Border Technologies",
    ministry: "Department of Military Affairs / ICAR",
    leadOfficerName: "Dr. A. Sharma (Director, ICAR)",
    independentValidatorName: "Prof. K. Rao (Aerospace, IIT Delhi)",
    status: "Active",
    durationWeeks: 8,
    startDate: "2026-09-15",
    totalBudget: 2850000,
    performanceScore: 94.2,
    milestones: [
      {
        id: "m-01",
        pilotId: "plt-01",
        sequence: 1,
        title: "Bench Calibration & Optical Sensor Synchronization",
        description:
          "Benchtop synchronization of SWIR and thermal cameras with Jetson Orin edge board; verification of timestamp precision (<5ms offset).",
        targetKPI: "Dual-stream FPS ≥ 30 with frame-drop rate < 0.1%",
        achievedKPI: "Achieved 32.4 FPS with 0.02% frame-drop over 24-hr continuous run.",
        deliverableDueWeek: 2,
        deliverableFileUrl: "/deliverables/M1_Bench_Calibration_Report.pdf",
        trancheAmount: 855000,
        tranchePercentage: 30,
        status: "verified",
        verifiedBy: "Prof. K. Rao (IIT Delhi)",
        verifiedAt: "2026-09-29 16:30 IST",
        verificationRemarks:
          "Optical latency benchmark verified on hardware oscilloscope. All timestamp synchronization criteria met without deviation.",
      },
      {
        id: "m-02",
        pilotId: "plt-01",
        sequence: 2,
        title: "Field Flight Trials under Sub-Tropical Canopy",
        description:
          "Live test flights across simulated forest testbed in Dehradun; penetration of dense Sal tree canopy at 60m–100m AGL.",
        targetKPI: "False positive detection rate < 8% under cloudy canopy conditions",
        achievedKPI: "5.4% false positive rate observed across 18 flight passes.",
        deliverableDueWeek: 5,
        deliverableFileUrl: "/deliverables/M2_Canopy_Flight_Log.pdf",
        trancheAmount: 1140000,
        tranchePercentage: 40,
        status: "submitted",
      },
      {
        id: "m-03",
        pilotId: "plt-01",
        sequence: 3,
        title: "Encrypted Mesh Telemetry & Ground Alert Handoff",
        description:
          "Full end-to-end rehearsal transmitting automated threat alerts to military field tactical tablet over 5km distance without cell coverage.",
        targetKPI: "Alert packet latency < 1.2s at 5km range with zero unencrypted leaks",
        deliverableDueWeek: 8,
        trancheAmount: 855000,
        tranchePercentage: 30,
        status: "pending",
      },
    ],
  },
];

export const SEED_SCALE_SOLUTIONS = [
  {
    id: "scale-01",
    pilotCode: "PLT-2025-084",
    title: "Intelligent Acoustic Sensor Mesh for Wild Elephant Herd Early Warning",
    startupName: "VanaRakshak AI Systems Pvt Ltd",
    dpiitNumber: "DIPP51280",
    originatingDepartment: "Department of Environment & Forests, Govt of Assam",
    validationDate: "2025-11-20",
    performanceScore: 96.8,
    deployedUnits: 45,
    budgetPerUnit: "₹1,80,000",
    summary:
      "Solar-powered acoustic nodes deployed along railway corridors in Kaziranga. Accurately detected elephant herd trumpet and footstep vibrations 800m ahead of tracks, cutting train-wildlife collisions to zero in the trial division.",
    gfrExemptionClause: "GFR 149 (ii) Validated Innovation Direct Requisition",
  },
  {
    id: "scale-02",
    pilotCode: "PLT-2026-003",
    title: "AI Edge Diagnostic Spirometer for Primary Health Centres",
    startupName: "ShwasTech Medical Devices Pvt Ltd",
    dpiitNumber: "DIPP63194",
    originatingDepartment: "Department of Health & Family Welfare, Govt of Odisha",
    validationDate: "2026-03-12",
    performanceScore: 93.5,
    deployedUnits: 120,
    budgetPerUnit: "₹45,000",
    summary:
      "Handheld digital spirometer with offline edge diagnosis for COPD and pulmonary fibrosis. Tested on 4,200 rural patients across Mayurbhanj district with 94.1% physician concurrence.",
    gfrExemptionClause: "GFR 149 (ii) Validated Innovation Direct Requisition",
  },
];

export const SEED_REPLICATION_REQUESTS: ReplicationRequest[] = [
  {
    id: "rep-01",
    pilotId: "scale-01",
    solutionTitle: "Intelligent Acoustic Sensor Mesh for Wild Elephant Herd Early Warning",
    startupName: "VanaRakshak AI Systems Pvt Ltd",
    originatingDepartment: "Dept of Environment & Forests, Assam",
    requestingDepartment: "Forest Department, Govt of Tamil Nadu",
    requestingOfficerName: "Shri R. Annamalai (Chief Conservator of Forests)",
    requestingOfficerEmail: "ccf.coimbatore@tn.gov.in",
    targetDeploymentSite: "Coimbatore-Palakkad Railway Line",
    targetQuantity: 30,
    requestedAt: "2026-08-14",
    status: "approved",
  },
];
